### ISSUE TITLE
sina模拟登陆无法登陆

### ISSUE THREAD

**Issue by BARKTEGH** [csuldw/WSpider#1]
经过测试，login登陆没有问题，但是login2会出现下面的错误
2016-12-30 11:10:18,026 | SinaClient | INFO | Start to login...
No JSON object could be decoded
Traceback (most recent call last):
  File "SinaSpider.py", line 180, in <module>
    testLogin2()
  File "SinaSpider.py", line 176, in testLogin2
    info = session.openURL("http://weibo.com/1669282904/info")
  File "SinaSpider.py", line 132, in openURL
    return self.unzip(text)
  File "SinaSpider.py", line 154, in unzip
    data = gz.read()
  File "F:\python2.7\lib\gzip.py", line 261, in read
    self._read(readsize)
  File "F:\python2.7\lib\gzip.py", line 303, in _read
    self._read_gzip_header()
  File "F:\python2.7\lib\gzip.py", line 197, in _read_gzip_header
    raise IOError, 'Not a gzipped file'
IOError: Not a gzipped file

password无法输入将get改为raw_input即可

**Comment by csuldw** [comment]
调用login2的时候，需要将openURL里面的返回内容修改下，不需要self.unzip()方法

def openURL(self, url, data=None):
        req = urllib2.Request(url, data=data, headers=self.headers)
        text = urllib2.urlopen(req).read()
        return text

另外password并非无法输入，是密码不显示出来，跟登录linux一样的

**Comment by BARKTEGH** [comment]
你好，我经过调试后，发现是在
jsonText = json.loads(resText)
出出现问题，No JSON object could be decoded，
发现好像是jsontext乱码了，无法读取出来。
login有一个问题在testLogin中session最后要用get方式才能得到是数据，post的话无法得到数据，
而是进入游客系统，并没有登陆进去。改用follow = session.get("http://weibo.com/u/%s/home" % uid).text.encode("utf-8")
就可以以登陆方式访问微博。

 最后非常感谢你的文章，让我学到了很多的东西，非常感谢。
2016-12-30 

zl19952013 



发件人：Diwei Liu <notifications@github.com>
发送时间：2016-12-30 15:48
主题：Re: [csuldw/WSpider] sina模拟登陆无法登陆 (#1)
收件人："csuldw/WSpider"<WSpider@noreply.github.com>
抄送："BARKTEGH"<zl19952013@163.com>,"Author"<author@noreply.github.com>

调用login2的时候，需要将openURL里面的返回内容修改下，不需要self.unzip()方法
def openURL(self, url, data=None):
req = urllib2.Request(url, data=data, headers=self.headers)
text = urllib2.urlopen(req).read()
return text

**Comment by csuldw** [comment]
恩，问题解决了就好，不客气。

我这边倒是可以正常运行，有时间我再看看代码。
