### ISSUE TITLE
您好，新浪微博登录的脚本求助

### ISSUE THREAD

**Issue by mengxue-rs** [csuldw/WSpider#2]
我把您的SinaSpider的登录url改成最新的
#登录时请求的url
login_url = r'https://login.sina.com.cn/sso/login.php?client=ssologin.js(v1.4.18)'
然后改成输出下面的内容http://weibo.com/
结果输出testLogin里的follow显示遇到了Sina Visitor System(表示登录失败),请问如何解决？
如果您有空回答我的问题，我将非常感谢！
如果您愿意发邮件联系我，我的邮箱是m15150682077@qq.com

**Comment by mengxue-rs** [comment]
您好，我已经解决了，感谢您的脚本

**Comment by xinweb4** [comment]
为啥检测有病毒···

**Comment by csuldw** [comment]
有病毒？

**Comment by ablebodied** [comment]
楼主怎么解决的呢？我的也是这样的，follow里面显示的是登录，说明没登录上，问题在哪里呢？
----------------------------------------------------------------------------------------------------------
####  _**已解决，把url从.cn改为.com就可以了！！**_

**Comment by csuldw** [comment]
好久没维护了，抱歉了 各位
