### ISSUE TITLE
您好，想问一下密码加密的10001怎么知道是十六进制的呢？

### ISSUE THREAD

**Issue by ablebodied** [csuldw/WSpider#4]
又怎么知道在Python代码里面将10001转为十进制的呢？
还有Fiddler里面/sso/login.php 这个里面看不到header，是一片空白

**Comment by Foamtor** [comment]
https://login.sina.com.cn/js/sso/ssologin.js中
` password = sinaSSOEncoder.hex_sha1("" + sinaSSOEncoder.hex_sha1(sinaSSOEncoder.hex_sha1(password)) + me.servertime + me.nonce)`

hex 指的就是十六进制

**Comment by csuldw** [comment]
closed
