### ISSUE TITLE
这是怎么回事呢？

### ISSUE THREAD

**Issue by ablebodied** [csuldw/WSpider#5]
代码中的gbk都注释掉了或改掉了，都没有gbk还报这个
`Traceback (most recent call last):
  File "SinaSpider.py", line 205, in <module>
    testLogin()
  File "SinaSpider.py", line 189, in testLogin
    client.output(follow, "out/follow.html")
  File "SinaSpider.py", line 160, in output
    fw.write(content)
UnicodeEncodeError: 'gbk' codec can't encode character '\xb5' in position 698: illegal multibyte sequence`

**Comment by csuldw** [comment]
你把client的output方法里的转码代码替换掉试试
